secret_key_base: yHVj18hRIAOzszmOMATU4oNcFNRL769SIuH3lA0lbPM
port: 3000
name: demo
log: "::Logger.new(STDOUT)"
log_level: "::Logger::INFO"
color: true
host: 0.0.0.0
port_reuse: false
process_count: (ENV[%(AMBER_PROCESS_COUNT)]? || 1).to_i
ssl_key_file:
ssl_cert_file:
redis_url: "redis://localhost:6379"
session:
  key: amber.session
  store: :signed_cookie
  expires: 0
secrets:
  description: Store your development secrets credentials and settings here.
  database: mysql://root@localhost:3306/demo_development
